//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_06.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class order_items
    {
        public int order_id { get; set; }
        public int item_id { get; set; }
        public int product_id { get; set; }
        [DisplayName("Quantity")]
        public int quantity { get; set; }
        [DisplayName("List Price")]
        public decimal list_price { get; set; }
        public decimal discount { get; set; }
    
        public virtual product product { get; set; }
        public virtual order order { get; set; }
    }
}
